### PR TITLE
Bug fix AttributeError of QDialog, unique feature id, OSX build instructions

### PR DESCRIPTION
**Pull request by BerginJay**
**Changes**

1. In PyQt4, QDialog and QFileDialog is in QtGui. As for PyQt5, QDialog and QFileDialog had moved form QtGui to QtWidgets. I changed a little bit so that this plugin can be imported correctly.

2. By default, circle-craters can only create features with fid=0. This can cause truble when edit a gpkg file, since fid must be unique in gpkg files. I left feature id without assignment. So for .shp files, fid is NULL, and for .gpkg files, fid is assigned automatically.

3. Updated collinearity condition, so it can avoid precision loss at small scale when using geographic coordinate systems which use degrees as distance unit instead of local projection coordinate systems, though custom projection coordinate system is recommended for better precision.  
By doing so, Circle Craters can be used for small crater or rock counting in high resolution images with a relative high precision in geographic coordinate systems

4. Using project specified ellipsoid when layer specified ellipsoid is not available, and prompt used ellipsoid and crs in export file header.

4. Add build instructions and some other information.

It has been test on both QGIS 3.10 and QGIS 3.16 on MacOS 10.15.7. 

Tested functions: start and stop counting, circling multiple craters and export data.

@sbraden @afrigeri  Thank you for your contribution. I'm not very familiar with PyQGIS and PyQt, please let me know if there is anything wrong.

### CODE REVIEW

**Comment by sbraden** [comment]
Hi @BerginJay! First, thank you for your work on this pull request! I'm going to test your updates and review.

**Comment by AlliedToasters** [comment]
hey! I'm new to this project but I had problems installing the plugin for PyQt5 + qgis 3.14 using the master branch - the pull request seems to install without errors for me on ubuntu 20.04! I haven't tested anything but might want to merge this if it looks ok @sbraden , thank you!!

**Comment by BerginJay** [comment]
> hey! I'm new to this project but I had problems installing the plugin for PyQt5 + qgis 3.14 using the master branch - the pull request seems to install without errors for me on ubuntu 20.04! I haven't tested anything but might want to merge this if it looks ok @sbraden , thank you!!

Thanks! Please let me know if there is anything wrong with this plugin. To get the right distance, please be careful with projection, coordinates and ellipsoid, it took me a long time to get the right crater diameters.

**Review by sbraden — APPROVED** [review]
I tested the changed against QGIS version 3.16.3-Hannover. The plugin installed correctly without errors.

**Pull request merged**
